name: movie_app
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-252.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  card_swiper: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

